### ISSUE TITLE
Quotes are not random when playing online

### ISSUE THREAD

**Issue by soywod** [rmehri01/thock#4]
When playing offline, the random works well. But online it seems to be the same quote coming over and over again:

```
You should just get a van. With a van, it's like you've got an MBA - but you've also got a van. You're not just a man anymore. You are a man with a van. If you get a van, Jez, we could be men with ven.
```

**Comment by soywod** [comment]
In fact it seems to be the expected behaviour, since a random quote is generated when the server starts:

```haskell
-- | Runs the websocket server with a random quote and initial state
runServer :: Int -> IO ()
runServer port = do
  q <- generateQuote
  st <- newMVar (newServerState q)
  WS.runServer "0.0.0.0" port $ serverApp st
```

It could be a nice feature to generate a random quote when starting a game instead, what do you think?

**Comment by rmehri01** [comment]
Oh yeah for sure, must have been something I overlooked. I can change it, thanks!
