### ISSUE TITLE
Addition of Thock to Brick README?

### ISSUE THREAD

**Issue by jtdaugherty** [rmehri01/thock#7]
Hi, I'm the author of `brick` and I came across your project on Twitter. It's super cool and I was wondering if you would be okay with me adding it to the Brick README's list of featured projects.

**Comment by rmehri01** [comment]
Hi, that would be great, thank you! :)

**Comment by jtdaugherty** [comment]
Done!

https://github.com/jtdaugherty/brick#featured-projects
